### ISSUE TITLE
Links Not Validating for min-width and min-height.

### ISSUE THREAD

**Issue by dbltoe** [lat9/ZCA-Bootstrap-Template#460]
It seems we stumble over something new every time we look at a site.

When using Siteimprove's checker, we found that many of the links on the site did not have the minimum height or width required for accessibility. It provides the mobile user with sufficient space so as not to click more than one link at a time.

Our suggested fix is to add the following to the basic "a" rule:

`display: inline-block;
    min-width: 44px;
    min-height: 44px;`

Those three appear to fix the problem sitewide without messing with any specific link on the site.

Let us know if you need confirmation in any specific area.

**Comment by dbltoe** [comment]
Further page diving resulted in a lot of the buttons having the same result. Adding button took care of that one as well.

**Comment by lat9** [comment]
I've not seen submission of a similar issue for the base Zen Cart.  Does this issue not also apply to the built-in responsive classic template?

**Comment by dbltoe** [comment]
Sorry for the delay in answering.  This applies to responsive_classic as well and has been fixed in the version at zencartdemo.com

**Comment by lat9** [comment]
> > Sorry for the delay in answering. This applies to responsive_classic as well and has been fixed in the version at zencartdemo.com
> 
> Please point me to the base Zen Cart issue that corrects this.

Still not seeing the base Zen Cart issue that addresses this issue.
